openapi: 3.0.0
info:
  title: Countries API
  version: 1.1
paths:
  /api/countries/single/{country}:
    get:
      summary: Get information for a single country
      parameters:
        - name: country
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Country information retrieved successfully
  /api/countries/all:
    get:
      summary: Get information for all countries
      responses:
        200:
          description: List of all countries retrieved successfully
  /api/countries/{country}:
    patch:
      summary: Update country information
      parameters:
        - name: country
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subregion:
                  type: string
                region:
                  type: string
                population:
                  type: integer
      responses:
        200:
          description: Country information updated successfully
    post:
      summary: Create a new country
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                flags:
                  type: object
                  properties:
                    svg:
                      type: string
                    png:
                      type: string
                translations:
                  type: object
                name:
                  type: string
                topLevelDomain:
                  type: array
                  items:
                    type: string
                alpha2Code:
                  type: string
                alpha3Code:
                  type: string
                callingCodes:
                  type: array
                  items:
                    type: string
                capital:
                  type: string
                altSpellings:
                  type: array
                  items:
                    type: string
                subregion:
                  type: string
                region:
                  type: string
                population:
                  type: integer
                latlng:
                  type: array
                  items:
                    type: number
                demonym:
                  type: string
                area:
                  type: integer
                timezones:
                  type: array
                  items:
                    type: string
                borders:
                  type: array
                  items:
                    type: string
                nativeName:
                  type: string
                numericCode:
                  type: string
                currencies:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: string
                      name:
                        type: string
                      symbol:
                        type: string
                languages:
                  type: array
                  items:
                    type: object
                    properties:
                      iso639_1:
                        type: string
                      iso639_2:
                        type: string
                      name:
                        type: string
                      nativeName:
                        type: string
                flag:
                  type: string
                regionalBlocs:
                  type: array
                  items:
                    type: object
                    properties:
                      acronym:
                        type: string
                      name:
                        type: string
                      otherAcronyms:
                        type: array
                        items:
                          type: string
                      otherNames:
                        type: array
                        items:
                          type: string
                cioc:
                  type: string
                independent:
                  type: boolean
      responses:
        201:
          description: Country created successfully

    delete:
      summary: Delete a country
      parameters:
        - name: country
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Country deleted successfully
